### ISSUE TITLE
Update Schematron to latest HL7 validation file

### ISSUE THREAD

**Issue by adunsulag** [openemr/oe-schematron-service#3]
HL7 has a new validation file available here: https://github.com/HL7/CDA-ccda-2.1/tree/master/schematron 

Our CDA validations are not matching what is coming out of the Edge Testing Tool (ETT). Looking at HL7's schematrons it looks like it was updated 20 days ago.  We need to use the latest version and hopefully that will catch the errors that were not being caught previously by our schematron validation.

**Comment by sjpadgett** [comment]
cool let me test as i'm looking over now

**Comment by adunsulag** [comment]
I'm just pushing out the PR now.

**Comment by adunsulag** [comment]
@sjpadgett Can you add me to the packagist for this package or create a new release 1.1.1 on packagist so we can get the update?

**Comment by sjpadgett** [comment]
yeah, let me catch up with you first. I pulled new rules and am testing now. Then i'll pull this, publish and add you to account.

**Comment by sjpadgett** [comment]
@adunsulag any reason you didn't include new voc.xml?

**Comment by adunsulag** [comment]
@sjpadgett I downloaded the file and it was the exact same as what was in the repository.

**Comment by sjpadgett** [comment]
okay however so far not making a difference in results. I'm not even getting warning so something is off.
I'm going to go ahead and publish this and continue testing.

**Comment by adunsulag** [comment]
yea, I'm not seeing any changes as well.  Trying to figure out if there is another validator as the ETT tools are failing the MDHT validation.  I would have thought the schematron would be doing whatever the MDHT validation is doing:

![image](https://user-images.githubusercontent.com/228117/172653001-b1c6af1c-e427-4eff-8b4b-3484a53fa236.png)

This is with the NT_Bad_AllergyConcernElements_r11_v3.xml in the full ETT CCDA 2.1 test deck.

**Comment by adunsulag** [comment]
@sjpadgett  Lovely... look at this thread.  ETT does not use the schematron at all.  It uses a completely different project called MDHT: https://groups.google.com/g/edge-test-tool/c/MsxjYmV5FJw/m/eERg2useBAAJ

**Comment by adunsulag** [comment]
https://github.com/onc-healthit/reference-ccda-validator/  is the validator rest API:

Here is how they call the API: https://github.com/onc-healthit/ett/blob/master/webapp/src/main/groovy/gov/nist/healthcare/ttt/webapp/direct/controller/CCDAValidatorController.groovy

Here is the library they are calling.  https://github.com/mdht/mdht

**Comment by sjpadgett** [comment]
Tomcat or scaredy cat!

![cat-gd7e5eeba3_640](https://user-images.githubusercontent.com/1859985/172663412-1d765e8c-b105-468b-9ee9-04e944f42a6b.png)

**Comment by stephenwaite** [comment]
I'm scared of that claw!

**Comment by sjpadgett** [comment]
That claw is for scratching my head!
